### ISSUE TITLE
Enhancement: mirror cursor position/selection when picker is opened with focusInput: true

### ISSUE THREAD

**Issue by momijizukamori** [mdbassit/Coloris#105]
Mostly because it feels like more intuitive behavior for end users? It's a quick change - after this line: https://github.com/mdbassit/Coloris/blob/main/src/coloris.js#L318 add `colorValue.setSelectionRange(currentEl.selectionStart, currentEl.selectionEnd, currentEl.selectionDirection);`. if the picker is configured with `selectInput: true` that still properly supersedes this and selects the entire input field.

**Comment by mdbassit** [comment]
I'm not sure what this is supposed to solve! Can you explain the issue you have?

**Comment by mdbassit** [comment]
I guess I didn't look closely. It looks to me like you want to mirror the selection from the original input field in the color picke's input field.

I will look into it.

**Comment by mdbassit** [comment]
That is indeed a sensible addition. Will implement soon. Thank you for suggesting it.
