### ISSUE TITLE
Materializecss compatibility

### ISSUE THREAD

**Issue by hoesman** [mdbassit/Coloris#125]
Could you make it compatible with materializecss? It kinda works with some problems, the inputs are buggin, the input where the color should be displayed is just showing the hex code and the input on the picker itself is misaligned and bugged

Here pictures, the second one is the desired square with the color
https://imgur.com/a/HO0smPU

**Comment by mdbassit** [comment]
Ah, another overzealous CSS framework!! 

If you are using the latest version of Coloris, add this code after you initialize it:

```js
Coloris.ready(() => {
  document.getElementById('clr-color-value').classList.add('browser-default');
});
```

**Comment by hoesman** [comment]
Thanks will give it a try, meanwhile i have been using the html type="color" which isnt that bad except for firefox using the ugly windows color picker, this is nicer and same across browsers
