### ISSUE TITLE
Mouse does not lineup on palette after scrolling in scrollable container

### ISSUE THREAD

**Issue by mikerowe81** [mdbassit/Coloris#127]
When the color picker is placed in a scrollable container and the container is scrolled after the color picker is opened, the mouse no longer lines up on the palette and is unusable.

https://jsfiddle.net/p0q7Lfzb/8/

**Comment by mikerowe81** [comment]
Just saw this previously reported in #18 
Let me know if I can help troubleshoot.

**Comment by mdbassit** [comment]
The `parent` option should point to the scrollable container itself, not to one of its children. I updated the jsfiddle to reflect that:
https://jsfiddle.net/Lvfj4w01/

Maybe I need to update the documentation to make that a bit clearer.

**Comment by leonardfischer** [comment]
@mdbassit that solution worked for me, thanks :)
