### ISSUE TITLE
add destroy

### ISSUE THREAD

**Issue by 3400442579** [mdbassit/Coloris#13]
add destroy  and   on("change"    )

**Comment by mdbassit** [comment]
@3400442579 do you mind to elaborate? What are you trying to accomplish?

**Comment by melloware** [comment]
`destroy` method is usually to clean a component and all its resources up and detach all listeners from any DOM elements.

`change` event so people can subscribe to the event when a new color is picked.

I am just guessing here. :)

**Comment by melloware** [comment]
From looking at your code I would image destroy would...

1. close the open popup if open.
2. Call `unbindFields` to reverse all your bindings in `bindFields` method
3. Call `unwrapFields` to reverse all the wrapping of fields in ` wrapFields(selector) `

**Comment by mdbassit** [comment]
An `input` event is fired on the original input field whenever a new color is picked, and a `change` event is fired on the original field when the color picker is closed.

As for the `destroy` method, I understand what it's technically supposed to accomplish. I'm asking whether it's necessary. I'm generally reluctant to implement features that would only cover rare edge cases.

So my question is this.. Once you decide that an input field is a color field, in which case would you decide it no longer needs to fill that role and should be reverted to a standard text field?

**Comment by melloware** [comment]
Yes that is typically what component libraries like jQuery Widgets do.  A `destroy` method puts the component back in its original state and remove all event handlers etc to be a good citizen.

As for the `change` and `input` events I agree no action there.

**Comment by mdbassit** [comment]
I understand that and I would have included it if this component created a separate instance for every color field, but that's not the case. There is a single instance of the component, and I use event delegation to attach the color picker to the active input field. 

As for destroying the main instance itself and removing its event listeners. I fail to see how this can be useful. I'm genuinely interested in learning about use cases where it can help, feel free to share if you know any.

**Comment by mdbassit** [comment]
That's because you are calling Coloris() with the option `el: '.coloris'` multiple times. In your case you should call Coloris() only once in your page. Normally there should only be 4 `click` and 2 `input` event listeners.

**Comment by mdbassit** [comment]
@3400442579 Did that solve your problem?

**Comment by 3400442579** [comment]
'<div style="background-color:#ddd;width:300px;padding:20px;position: relative;" class="container" ></div>"   Dynamically generated

**Comment by mdbassit** [comment]
@3400442579 I'm sorry, I don't understand your last comment, can you please explain?

**Comment by 3400442579** [comment]
https://codepen.io/3400442579/pen/yLzbXOQ

**Comment by mdbassit** [comment]
You are initializing `Coloris()` every time there is a click on "Set Colors". You should remove the `mounted()` method, and call `Coloris()` outside of `createApp()`:
```js
PetiteVue.createApp({
    color: '#ffffff',
    open: false,
    cls: [
        '#264653',
        '#2a9d8f',
        '#e9c46a',
        '#e76f51',
        'navy',
        '#07b',
        '#0096c7',
    ]
})
.directive('click-away', clickAwayDirective)
.mount();

// Configure Coloris
Coloris({
    parent: '.container',
    el: '.coloris',
    // wrap: true,
    theme: 'polaroid',
    themeMode: 'light',
    format: 'hex',
    formatToggle: false,
    alpha: true,
});
```
You also need to move the container class from the template to the parent div:
```html
<!-- replace this line -->
<div class="display: inline-block;" :style="{'background-color':color}">

<!-- with this line -->
<div class="container" :style="{'background-color':color}">
```
And make sure that container has a relative position:
```css
.container {
    position: relative;
}
```

**Comment by mdbassit** [comment]
I'll consider this resolved.
