### ISSUE TITLE
I would like to contribute sass/scss to the repository

### ISSUE THREAD

**Issue by MattOpen** [mdbassit/Coloris#132]
Dear @mdbassit,

I have rewritten the CSS part and transformed it into scss.
Actually I have only rewritten without any changes to the style and also not created variables. But I could do it later.
How can I participate on the project?

cheers Richard

**Comment by mdbassit** [comment]
Hello Richard,

I intentionally avoided using a CSS pre-compiler cause I need this to work on modern browsers without any building steps. But I thank you for your offer to contribute.

**Comment by MattOpen** [comment]
Dear Momo,

I don´t understand your point here.
The result is the same.
After my change, the distribution folder contains the pre compiled Coloris.css file (as of before).
![image](https://github.com/mdbassit/Coloris/assets/4366385/050e310c-a9b9-47bf-ba09-e22d9bccd654)

it is done by the task
`function watchFiles() {
  watch(path.js, minifyJS);
  watch(path.scss, parallel(transpileSCSS));
  watch(path.css, parallel(minifyCSS));
}`

**Comment by mdbassit** [comment]
I meant that today, I can include the source J's and css files to a page and they would work out of the box without any build step.

**Comment by MattOpen** [comment]
Dear Momo,
I got it. Then I will create a new fork and do the changes then.
Thank you :)

PS: then we can close this issue
