### ISSUE TITLE
The color picker doesn't stick to the input it scrolls along 

### ISSUE THREAD

**Issue by MeetM15** [mdbassit/Coloris#136]
![image](https://github.com/mdbassit/Coloris/assets/62867007/d99766b0-069c-4898-a010-3d46520c4d35)
![image](https://github.com/mdbassit/Coloris/assets/62867007/b4305f6b-83e0-499d-abb4-4992d76752f0)

**Comment by mdbassit** [comment]
The input fields are probably rendered within a scrollable container. You need to set the `parent` option to a selector pointing to that scrollable container.

**Comment by mdbassit** [comment]
@MeetM15 does this solve your problem?
