### ISSUE TITLE
Make `el` and `parent` options accept `Node`

### ISSUE THREAD

**Issue by silverwind** [mdbassit/Coloris#139]
These options only accepting selectors is problemantic when multiple matching elements are present on the page and one wants to use different coloris options per element.

It would be nice if these options would also accept [`Node`](https://developer.mozilla.org/en-US/docs/Web/API/Node) or [`NodeList`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) directly.

**Comment by mdbassit** [comment]
> These options only accepting selectors is problemantic when multiple matching elements are present on the page and one wants to use different coloris options per element.

Using different options for different color fields is exactly what [virtual instances](https://github.com/mdbassit/Coloris?tab=readme-ov-file#simulating-multiple-instances) are for. Check out the [demo page](https://coloris.js.org/examples.html) for examples.


> It would be nice if these options would also accept [`Node`](https://developer.mozilla.org/en-US/docs/Web/API/Node) or [`NodeList`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) directly.

I'm not opposed to adding support for both if necessary, but I fail to see how CSS selectors are insufficient. Would you mind explaining?

**Comment by mdbassit** [comment]
> but overall I think it should be made possible to create separate independent instances.

Unfortunately, that goes again the main reason Coloris was created in the first place. It is being used on a web app with dozens of other widgets and was designed to use the least amount of DOM elements and event listeners.

> With selectors, there is a race condition where content on the page changes between the time the selector string is passed to Coloris and when Coloris runs `querySelectorAll`.

Can you tell me more about that race condition? How can I reproduce it? I'd be happy to fix it if it's a bug.

**Comment by silverwind** [comment]
> Unfortunately, that goes again the main reason Coloris was created in the first place. It is being used on a web app with dozens of other widgets and was designed to use the least amount of DOM elements and event listeners possible.

Yeah I see and this is probably not an issue, but I can easily see that complex applications this shared global instance becomes a problem, especially the limitation of having only one picker open is problematic. Does not matter for my current use case, thought.

> Could you tell me more about that race condition? How can I reproduce it? I'd be happy to fix it if it's a bug.

The race condition is only theoratical. Overall JS is likely fast enough that it won't be reproducible.

 Fundamentally I would expect an lib like this to not use`document.querySelectorAll` at all. It's a [slow](https://dev.to/wlytle/performance-tradeoffs-of-queryselector-and-queryselectorall-1074) function that gets slower the more elements are in the DOM. It's much better to let the consumer decide to run it or not, because they likely have more efficient means.

**Comment by agolinko** [comment]
Hi
I’m voting for the acceptance of Node as a parent.

I’m developing a component that can be built into a ready application. My challenge is that I operate in an environment where I cannot control the CSS, and third-party CSS could potentially interfere with my component’s styles. Therefore, I want to encapsulate my component within a shadow DOM. Unfortunately, Coloris does not currently support this feature. It would be ideal if I could pass the shadow DOM root as the parent.

**Comment by silverwind** [comment]
Yes, Shadow DOM is a big use case, `document.querySelectorAll` by design can not reach into Shadow DOM because it acts as a CSS boundary. There are likely more similar boundaries, `<iframe>` is likely also affected.

**Comment by mdbassit** [comment]
> especially the limitation of having only one picker open is problematic.

That limitation is intentional and will not change. There are other open source color pickers out there that support multiple real instances.

> Fundamentally I would expect a lib like this to not use document.querySelectorAll at all. It's a [slow](https://dev.to/wlytle/performance-tradeoffs-of-queryselector-and-queryselectorall-1074) function that gets slower the more elements are in the DOM.

I'm aware of the performance overhead of `querySelectorAll`, but I judged that it was fast enough for this use case considering the benefit of handling complex CSS selectors.

It's important to note that his tool is **NOT** design to be a general purpose color picker that could cover every use case, it's designed to be a simple and fast color input field alternative.

Again, I'm not opposed to accepting a `Node` or a `NodeList` for the `el` and `parent` options. I will look into it, and if it doesn't interfere with my own use case, I will add it. 

I will not however be spending any time supporting what I judge as exotic use cases like shadow DOM or iframes. Feel free to fork this project and take in your own preferred direction if you disagree.

**Comment by silverwind** [comment]
Sure, keep it your way if it fits your use case and probably that of many others. Myself, I will be looking for alternatives that are better suited for my use cases.

**Comment by silverwind** [comment]
I've managed to switch to https://github.com/web-padawan/vanilla-colorful. It's certainly a bit more effort with manual creation of popover and previous square, so likely not for everyone.

**Comment by mdbassit** [comment]
Glad you found a color picker that works for you.

I'll keep this open to remind myself about the `Node` and `NodeList` support request.

**Comment by mdbassit** [comment]
Coloris now also accepts a `Node` for the `parent` option, and a `Node` or array of nodes for the `el` option.
`NodeList` and `HTMLCollection` must be converted to an array before passing it to `el`:

```js
Coloris({
  el: Array.from(document.getElementsByClassName('my-class')),
  parent: document.getElementById('my-parent')
});
```

**Comment by melloware** [comment]
Excellent work @mdbassit the Typescript version of 0.24.0 is now in NPMJS.
