### ISSUE TITLE
Publish on npm ?

### ISSUE THREAD

**Issue by VincentMolinie** [mdbassit/Coloris#14]
Do you plan to publish on npm 👼  ?

**Comment by mdbassit** [comment]
No, I do not :)

**Comment by melloware** [comment]
I have an npm account and publish other libraries. Any chance you would be interested if I release it to npm?

**Comment by mdbassit** [comment]
Feel free!

**Comment by melloware** [comment]
Its now available on NPM with TypeScript here: https://www.npmjs.com/package/@melloware/coloris
