### ISSUE TITLE
colorArea doesn't handle right mouse button

### ISSUE THREAD

**Issue by ut4** [mdbassit/Coloris#141]
**Steps to reproduce**:
1. Right-click on colorArea
2. Hit esc
3. Move the mouse

**Current Behavior**:
colorMarker continues moving

**Expected Behavior**:
colorMarker stays put

**Comment by mdbassit** [comment]
Thanks for reporting! I will release a fix soon.

**Comment by ut4** [comment]
Good to hear, thanks!
