### ISSUE TITLE
Feature Request: Add Eyedropper

### ISSUE THREAD

**Issue by av01d** [mdbassit/Coloris#142]
Chrome and Edge support a very cool new EyeDropper API. Could you add it to Coloris?
https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper

**Comment by mdbassit** [comment]
This has already been requested in #95.

My position on it hasn't changed, the EyeDropper interface is still experimental and is only supported in Chromium/Blink browsers. I will consider adding it when it matures and is supported by all modern browsers.

**Comment by av01d** [comment]
I didn't check the closed issues, sorry. Thanks for you reply!
