### ISSUE TITLE
Bug: problem with inline mode

### ISSUE THREAD

**Issue by AkramiPro** [mdbassit/Coloris#156]
![GIF 2024-07-20 22-37-49](https://github.com/user-attachments/assets/fe224518-257a-4fb8-901b-b7e79a0323cc)

reproduced in this demo:

https://codepen.io/AkramiPro/pen/OJeNorz

pr:  #155

**Comment by mdbassit** [comment]
This will fix your problem:
https://codepen.io/mbassit/pen/xxoVyPq

I basically just added a child div inside `.form-color-picker-wrap` and called it `.form-color-picker-wrap-inner` and gave it a width of 100%. I set the new div as the parent element of the color picker. The button on the left side and the `gap` property were interfering with the calculation of the position.

**Comment by AkramiPro** [comment]
Thanks for your reply.
but it is not better to support all situations ?
I think it is better to handle it on the js side instead of the client side.

**Comment by mdbassit** [comment]
Your PR fixes your use case but breaks the marker position for other cases. This tool is already being used in production, so any modification has to be thoroughly tested.

**Comment by AkramiPro** [comment]
you right
i will make a new pr after i test all possible ways
thanks for help
