### ISSUE TITLE
Possibility to change z-index in option

### ISSUE THREAD

**Issue by itajackass** [mdbassit/Coloris#157]
Hi, nice plugin!!
But there is a problem is the plugin is on a modal element.
Cause z-index is set to 1000, in some customized theme, the picker is covered by modal.
I suggest an option to set dinamically z-index based on needed.
Thanks

**Comment by mdbassit** [comment]
Thanks for the kind words. I think what you need is to set the `parent` option to the model dialogue. See https://github.com/mdbassit/Coloris/issues/100

**Comment by itajackass** [comment]
Ok i've seen now! Worked perfectly, thanks
