### ISSUE TITLE
Parent element positioning is incorrect

### ISSUE THREAD

**Issue by VincentMolinie** [mdbassit/Coloris#19]
# Description of the issue
When I specify the option `parent`, the picker is always display on top even if there is not enough space on top. 

# Example
```html
<div id="test-me" class="c-color-input">
  <input type="text" data-coloris/>
</div>
```
if I put "test-me" in parent the positionning is not correct

**Comment by mdbassit** [comment]
The picker will default to displaying on top when there is not enough space at the bottom. I'm unsure of what to do when there is not enough space on top either.

**Comment by VincentMolinie** [comment]
No I mean the issue is that you are calculating the position based on the parent  we pass instead of the first scrollable element.
Look at the screen:
<img width="266" alt="Capture d’écran 2021-11-10 à 09 05 21" src="https://user-images.githubusercontent.com/3263749/141074115-f3a7c828-348f-4488-b18e-667fbe3b3d21.png">
As you can see there is plenty of space on the bottom but instead the picker is placed on top because the height of parent is the height of the input 😅

**Comment by mdbassit** [comment]
In that case, the picker should be attached to the srollable parent

**Comment by mdbassit** [comment]
In that case the picker should be attached to the first scrollable parent.
