### ISSUE TITLE
[Feature request] Programmatically opening the dialog box

### ISSUE THREAD

**Issue by matty0005** [mdbassit/Coloris#24]
Hi, 
Is having an open() method (the reverse of what you have for the close() method) on your roadmap at all?
Thanks

**Comment by mdbassit** [comment]
Hi, I do not plan to add an `open` method, but that could be easily simulated by triggering a click on an input field to which the color picker is bound.

```js
Coloris({ el: '.my-color-field' });

// You might want to wait for the DOM to be ready before doing this
document.querySelector('.my-color-field').click();
```
