### ISSUE TITLE
Add option to use picker inline

### ISSUE THREAD

**Issue by jepsar** [mdbassit/Coloris#25]
In case of inline I don't want an input field to be visible, instead it should act as an input. Values can either be bound to a hidden input, or you simply have to listen for color picks and deal with values in the listener.

**Comment by melloware** [comment]
Agreed this would be nice

**Comment by mdbassit** [comment]
You mean you want the picker to be always visible and statically positioned?

**Comment by melloware** [comment]
@mdbassit yes similar to this example here: https://www.primefaces.org/showcase/ui/input/colorPicker.xhtml

**Comment by mdbassit** [comment]
I will see what I can do. I'm currently quite busy working on the original project where I needed a color picker in the first place.

**Comment by matty0005** [comment]
Is there any update on this? It would be a nice feature to have. 

Currently if you set the `type="hidden"` and have a seperate div/button to open the picker, it opens but in the wrong place - up the very top left hand corner.

**Comment by mdbassit** [comment]
Unfortunately I'm still too busy and haven't gotten a chance to work on it yet.

Please not that input fields of type `hidden` are not supported. You should use CSS to hide the input fields if you must (I recommend setting the opacity to 0).

**Comment by mdbassit** [comment]
Hi @jepsar, I'm finally getting around to implementing this, sorry that it took so long.
I should have a working version later today.

**Comment by melloware** [comment]
great work @mdbassit   Deployed 0.12.0 to NPM
