### ISSUE TITLE
Option to NOT focus on color value input by default

### ISSUE THREAD

**Issue by northernlite69** [mdbassit/Coloris#26]
Option to NOT focus on color value input by default because the focus automatically activates keyboard on mobiles, etc.

Also, maybe it's just me, but Option wrap=false is not working for me; result and swatch are still showing.

Thank you for your work- it's (almost) perfect!

**Comment by mdbassit** [comment]
Actually, that option has already been added in my local version. I'll push that change later today.
As for the wrap option, I'm not sure what you mean when you say the result and swatch are still showing. Could you share your code and a screenshot of what you get?

Thank you for the kind words!

**Comment by northernlite69** [comment]
Fantastic!  
Thank you! 
Seriously: Thee Best (esp mobile) ColorPicker, eva.

WRAP ISSUE

JS:

	Coloris({
		parent: '#editorNav',
		wrap: false,
		alpha: true,
		swatches: ['#ffff00',
			'#ff00d4',
			'#aaaaaa',
			'#fff',
			'#000']
	});

HTML:

<input class="quiInputColor" data-coloris type="text" value="#ff0000" >

The top input hangs off BODY.  The lower is inside a div with overflow:hidden.  Maybe I've misunderstood your directive, but I expect wrap=false to NOT show swatch and button.  I've redesigned my solution now, so this is not a *real* issue for me anymore, but I thought you might want to know.

Another suggestion- if it doesn't entail a heavy refactor- is an option to NOT anchor the picker to an input and just open it as a (modal) dialog with callback?  

You'd be surprised how many color pickers out there all constrain themselves to a field.  On smaller devices, the color popup will naturally consume most screen real estate so anchoring to a (potentially scrollable) input clunks the flow.  This ability will dramatically increase your pickers potential.







![Screenshot 2021-12-14 at 17-17-49 Freeble](https://user-images.githubusercontent.com/16082320/146049122-78fa883b-9740-45d4-a791-7160feb37143.png)

**Comment by mdbassit** [comment]
I see, I failed to mention in the doc that this option only works on a custom `el` selector and not on the default _[data-coloris]_ attribute selector. I will update the README file to point it out.

As for your other suggestion, I will consider it along with this #25 for a future release.
