### ISSUE TITLE
Reset or set specified color

### ISSUE THREAD

**Issue by BNO79** [mdbassit/Coloris#29]
I don't understand how it's possible to set a specified color at runtime, the only way i've found is by setting the input value, but when i open the colorpicker it show me the set value into the input box, but the previous color into the preview box, i'm italian sorry for ma bad english :)

**Comment by mdbassit** [comment]
Setting the value of the input is the right way, if this doesn't work for you it must be a bug. Can you please share your code so I can take a look?

**Comment by BNO79** [comment]
Hi and thank for the quick reply :)
In the following [url](http://jsfiddle.net/rpy0c9Lh/) i replicate my problem, the step are simply:
1) set a color
2) The checkbox "Apply color" will turn to checked
3) click "Reset color"
4) The checkbox "Apply color" will turn to un-checked, the color input torn #000000 but the preview color doesn't torn to black

**Comment by mdbassit** [comment]
I updated the JSFiddle and now it works:
http://jsfiddle.net/n4v8pk5o/

You need to trigger a real "input" event on the color field for it to work. Using the jQuery's trigger() method doesn't actually trigger a real DOM event.

**Comment by BNO79** [comment]
Perfect! Thank you so much!!!
