### ISSUE TITLE
Add option to show 'clear' button

### ISSUE THREAD

**Issue by nickygerritsen** [mdbassit/Coloris#3]
Would it be possible to add an optional clear button (or a 'x' or something) that will clear the input field? Currently when you set a color you can not remove it anymore (unless you manually tab to the original input field and delete it that way).

**Comment by mcki0127** [comment]
Would it be possible to add a default color on clear?  Css border colors default to black when no color is specified.  I would like the color picker to default to transparent when the clear button is picked.
