### ISSUE TITLE
Simple request :)

### ISSUE THREAD

**Issue by BNO79** [mdbassit/Coloris#30]
It would be useful if with a double click on a color (both of the palette or the custom colors) of the color picker, trigger the event that close the popup

**Comment by mdbassit** [comment]
I don't know if double click is a good idea, it doesn't work on mobile for one thing.
I was thinking of adding an option to automatically close the picker when a color swatch is clicked.

**Comment by BNO79** [comment]
For my use (my site is only for desktop user) will be better double click,
if you can add two parameter, one for enable single click and one for
double click i use the second one for this site and maybe the first one the
next time :)

Il lun 27 dic 2021, 02:41 Momo Bassit ***@***.***> ha scritto:

**Comment by mdbassit** [comment]
I still don't think double click is a good way of doing it, but if you would like to add it to your own website, add this code at the end of your page:
```js
document.addEventListener('dblclick', function (event) {
  if ( event.target.matches('.clr-swatches button, #clr-color-marker') ) {
    Coloris.close();
  }
});
```
This will close the color picker when you double click on the swatches or the spectrum.

**Comment by BNO79** [comment]
I'll try it when I'll return from my holidays in Sicilia :)
Thank so much and Happy new year!

Il gio 30 dic 2021, 02:08 Momo Bassit ***@***.***> ha scritto:
