### ISSUE TITLE
Add possibility to show only the swatches, without spectrum / alpha.

### ISSUE THREAD

**Issue by fabiocaccamo** [mdbassit/Coloris#31]

**Comment by mdbassit** [comment]
So you want to hide the spectrum, the alpha, the color value field and everything else except the swatches?
What will be left is just a popup with a few color swatches?

**Comment by fabiocaccamo** [comment]
Exactly! This is very useful when you need to constrain the user choice to some predefined colors.

**Comment by mdbassit** [comment]
I will add the option in a future version.

**Comment by fabiocaccamo** [comment]
🚀
