### ISSUE TITLE
Thumbnails do not work in dynamic created content.

### ISSUE THREAD

**Issue by Roinoss** [mdbassit/Coloris#33]
In static part of the page example code transforms from:
A:
```
<div class="example full">
  <p>Full size thumbnail</p>
  <input type="text" class="coloris" value="#ffcc00">
</div>
```
To:
B:
```
<div class="example full">
        <p>Full size thumbnail</p>
        <div class="clr-field" style="color: rgb(255, 204, 0);">
              <button aria-labelledby="clr-open-label"></button>
              <input type="text" class="coloris" value="#ffcc00">
        </div>
</div>
```
In dynamic created content thumbnail stays A, but color picking tool works in both cases.

**Comment by Roinoss** [comment]
Ok, idiotic obvious answer - reload all Coloris with same options.

**Comment by mdbassit** [comment]
Actually a better way would be to call the Coloris.wrap() method with your selector as an argument every time you generate HTML code dynamically. This has the advantage of not adding the event listeners on your selector multiple times.

```js
Coloris.wrap('.coloris');
```

**Comment by Roinoss** [comment]
Thanks!
This answer would be nice to have in README.

**Comment by mdbassit** [comment]
I didn't include it in the README file on purpose as I might change the way that works. I avoid documenting features that are likely to be altered in the future.
