### ISSUE TITLE
disable spellcheck for input "clr-color-value" and ability to hide "clr-preview"

### ISSUE THREAD

**Issue by SuperDOS** [mdbassit/Coloris#34]
Love this color picker, thanks!

Would be great to add spellcheck="false" for `<input id="clr-color-value" class="clr-color" type="text" value="" aria-label="Color value field">`

also if there was an option to hide the live preview now I've done it with css
`.clr-preview{display:none;}`

![image](https://user-images.githubusercontent.com/7214952/156435302-62cc5443-1e98-4bcb-bb64-1a7b90689129.png)

**Comment by mdbassit** [comment]
Thank you for your feedback!

I personally haven't encountered a case where the browser will try and spell check the color value, but it wouldn't hurt to add `spellcheck="false"` to it. I'll do it later today.

As for the color preview, I don't think removing it will be right for most people, and your workaround of removing it with CSS is the right way to deal with it anyway.

**Comment by SuperDOS** [comment]
Thanks!

I'll hide it with css then, in my case since I get a live preview from the input selector so I found the color preview unnecessary and also wanted to be able to show the complete rgba code. :)
