### ISSUE TITLE
too many decimals when setting a RGBa value

### ISSUE THREAD

**Issue by SuperDOS** [mdbassit/Coloris#35]
When setting a RGBa value with for example $("#colorpicker").val("rgba(47, 47, 47, 0.36)")
the value in the color picker is rgba(47, 47, 47, 0.36078431372549)
![image](https://user-images.githubusercontent.com/7214952/157134867-e5c4f88c-6b05-47cb-8fd7-e28582304fc7.png)

is there some bug that set the alpha value with 14 decimal places or is it an issue with jquery?

Thanks

**Comment by mdbassit** [comment]
I'm unable to reproduce this behavior. Could you share a page where I can try your version?

**Comment by SuperDOS** [comment]
Sure have a look here [https://jsfiddle.net/SuperDOS/dyg01eqL/12/](url)
The input field is correct but not in the input.clr-color field
![image](https://user-images.githubusercontent.com/7214952/157186432-2a2fca40-9e0f-4567-8fda-dcfae3825da4.png)

**Comment by mdbassit** [comment]
That looks like a Chrome bug as I'm unable to reproduce it on Firefox or Safari. I will see what I can do to mitigate it.

**Comment by mdbassit** [comment]
It is indeed a Chrome/Chromium bug and it's already been reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=1300389
I'm thinking of a workaround now, I will let you know when/if a fix is available.

**Comment by mdbassit** [comment]
A fix has been released. I will revert it when Chromium fixes the bug.
