### ISSUE TITLE
How to refresh color after 

### ISSUE THREAD

**Issue by arnaudboi** [mdbassit/Coloris#4]
![image](https://user-images.githubusercontent.com/19311945/137731124-6023f243-2908-4a39-a4e5-c9115ff41804.png)

Hello, how can i refresh the clr-open-label ? 
I use the same field and i need to update him (the only thing who dont refresh is the label).

Thanks !

**Comment by mdbassit** [comment]
@arnaudboi Was your problem resolved? Let me know so I can close this issue.

**Comment by mdbassit** [comment]
I see! You update the value of the color field programmatically with jQuery. In that case, all you need to do is to trigger an "input" event on the field:

```js
jQuery("input[name=edit_date_type_couleur]").trigger("input");
```

You don't need to call Coloris.wrap() anymore.

**Comment by mdbassit** [comment]
I just took a look at the code for jQuery.trigger() and it seems it only works for event listeners created with jQuery. So what you need is to trigger an "input" event with vanilla JavaScript. Try this code right after you change the color value:

```js
document.querySelector("input[name=edit_date_type_couleur]").dispatchEvent(new Event('input', { bubbles: true }));
```

I hope this time it works.
