### ISSUE TITLE
Request for event "open" and "close"

### ISSUE THREAD

**Issue by giacomarco** [mdbassit/Coloris#40]
Sorry for my english.

Thank you for your work and it's a wonderful project.

If you can i need more events for example "open" and "close" 

change event not trigger on close if there's no change color. 
In local i add `currentEl.dispatchEvent(new Event('close', { bubbles: true })); ` on line 290
and  `currentEl.dispatchEvent(new Event('open', { bubbles: true }));` on line 184

Thank you so much , Marco

**Comment by jepsar** [comment]
Won't focus and change on the input do?

**Comment by giacomarco** [comment]
no because i'm not using input as "trigger" but a button with value.

**Comment by mdbassit** [comment]
While I don't agree with not using an input field as a trigger, I don't see any harm in adding an `open` and `close` events. I'll push an update later today.

**Comment by giacomarco** [comment]
thank you so much, i agree with you that's better to use with input field as trigger but i use in a richeditor and I must to uniform the style of buttons. Thank you @mdbassit for your supports

**Comment by melloware** [comment]
This is now available on NPM as v 0.11.0 : https://www.npmjs.com/package/@melloware/coloris

Excellent work @mdbassit

**Comment by mdbassit** [comment]
Thank you @melloware for your help with the NPM package.
