### ISSUE TITLE
Select value option

### ISSUE THREAD

**Issue by jonkrauss** [mdbassit/Coloris#41]
Thanks so much for developing this tool. It's super useful, easy, and attractive. Really nice work.

An enhancement idea... A setting 'selectInput' for selecting the color value text when the popup opens. This would save extra clicks to type or paste in a color value.

In the bindFields method:

```
if (settings.selectInput){
    colorValue.select();
}
```

**Comment by mdbassit** [comment]
Thanks for the kind words!
Would you like to submit a pull request that implements this?

**Comment by mdbassit** [comment]
@jonkrauss are you still interested in implementing this, or should I close this issue?

**Comment by jonkrauss** [comment]
Thanks for following up. It’s up to you. I’m not sure how to do what you requested. 

Cheers,
Jon
