### ISSUE TITLE
Inline colorpicker not calculating the right area dimensions #62

### ISSUE THREAD

**Issue by JacobDeuchert** [mdbassit/Coloris#42]
I want to display the colorpicker in a custom popup without any input. I used the following options:

    Coloris({
      el: null,
      inline: true,
      parent: '#' + anchorId,
      autoClose: false,
      focusInput: false,
      alpha: false,
    })

![coloris](https://user-images.githubusercontent.com/43518397/165992914-6b911180-b704-4528-9535-57bc54bdc846.gif)

I reproduced the bug in this [Codepen](https://codepen.io/jacobdeuchert/pen/eYVOPQN)

The colorpicker opens as expected but when using the colorArea the color marker is locked to the right of the area because the x / y dimensions getting calculated are a bit off in the updatePickerPosition() function. I fixed it by using getBoundingClientRect() for the dimensions. I can provide the fix as a PR but it probably needs some testing with other use cases.

**Comment by melloware** [comment]
please provide a PR for review thanks!

**Comment by mdbassit** [comment]
Sorry, I was already aware of the issue and I have a fix. I didn't get around to pushing it as I have been on a few flights the past couple days. I will push an update soon.

**Comment by JacobDeuchert** [comment]
Sorry did not check the issue again and created a PR. I will leave the PR open so you can compare if you want.

**Comment by mdbassit** [comment]
I pushed a new release to fix this issue.
