### ISSUE TITLE
Not working with bootstrap Modal

### ISSUE THREAD

**Issue by Aks8578** [mdbassit/Coloris#45]
Coloris picker not working with latest bootstrap 5 Modal.
And not able to focus or edit color input in bootstrap 5 Modal popup.

I tried to fix it with z-index but not able to edit input hex text.

Please help me out Sir.

**Comment by mdbassit** [comment]
Please share a demo page so I can see the problem and help you fix it.

**Comment by Aks8578** [comment]
[https://codepen.io/aditya8578/pen/poagbOq](url)

**Comment by mdbassit** [comment]
You just need to increase the value of the z-index of the color picker dialog. Add this code to your CSS:
```css
.clr-picker.clr-open {
  z-index: 10000;
}
```

**Comment by Aks8578** [comment]
But the manual color input field not working.

**Comment by mdbassit** [comment]
I don't understand what you mean!

**Comment by Aks8578** [comment]
<img width="958" alt="coloris" src="https://user-images.githubusercontent.com/92620037/167259086-372732dd-bb42-4a67-88d9-55b5b0177337.png">


Please Look At this Image.

**Comment by mdbassit** [comment]
That's an issue with bootstrap, not with the color picker. It seems the bootstrap modal forces focus inside it whenever it loses focus, which means that the input field inside the color picker (which is outside the modal) can not be focused and thus can not be edited.

**Comment by Aks8578** [comment]
Do you have solution to it?

**Comment by mdbassit** [comment]
Depending on how you want to use the color picker, you can try and render it inside the modal dialog. Add this code to the bottom of your page:
```js
Coloris({
  parent: '#myModal'
})
```

**Comment by Aks8578** [comment]
Thanks you Very much, It works.

**Comment by Aks8578** [comment]
One more thing Sir
How to design input field just like in your demo page (Rounded square thumbnail).

**Comment by mdbassit** [comment]
Check out the file examples.html, there are code snippets you can use.

**Comment by Aks8578** [comment]
Thanks Sir
