### ISSUE TITLE
The `button` element submits the form when clicked

### ISSUE THREAD

**Issue by savissimo** [mdbassit/Coloris#46]
Thank you for this component! It's so easy to setup and get working, it's really great! 

But there's a problem: I made Coloris pickers out of my `<input type="text" />` elements inside a form. When I closed the picker, the form got submitted. After inspecting, I've noticed that a `button` element is created, but since it has no `type` attribute it is assumed to be `type="submit"`. 

Can you set a default `type="button"` attribute, please?

**Comment by mdbassit** [comment]
Thank you for the bug report, indeed I haven't tested the color picker inside a form. I will release a fix in a bit.

**Comment by mdbassit** [comment]
Merged. Thanks for the PR!
