### ISSUE TITLE
Add color syntax toggle

### ISSUE THREAD

**Issue by jepsar** [mdbassit/Coloris#5]
Something like how it's done in the Chrome developer tools:

<img width="284" alt="Screenshot 2021-10-22 at 09 20 38" src="https://user-images.githubusercontent.com/7500178/138414476-a66b2c76-5ad3-4797-a331-9951971f6f74.png">

**Comment by mdbassit** [comment]
@jepsar I'm finally working on adding this feature, it will look like the screenshot bellow.
It was a bit tricky to add it in an accessible way, but I'm almost done.

<img width="253" alt="Format switcher feature" src="https://user-images.githubusercontent.com/6975607/140460520-167538c8-54a0-408e-a4fa-c1a96eb48daf.png">

**Comment by jepsar** [comment]
Looking great so far
