### ISSUE TITLE
Manual update of preview thumbnail

### ISSUE THREAD

**Issue by neiltking** [mdbassit/Coloris#53]
Loving Coloris. It is small, easy to implement and works great.

There is one problem I haven't been able to solve. I update the input field with a hex value programmatically, for example:
`$("#colour").val("#FFFFFF");`
But the Coloris thumbnail remains the transparent chequerboard pattern. Is there a way to force the thumbnail to update its colour when I programmatically change the value in the input field? I have tried calling Coloris.close() as there is mention in the source code that it might force an update of the thumbnail but this doesn't work for me.

Thanks.

**Comment by mdbassit** [comment]
Thank you for the kind words!
The thumbnail is updated when an `input` event is triggered on the input field. You need to trigger it manually in your case using this code:

```js
 $("#colour")[0].dispatchEvent(new Event('input', { bubbles: true }));
```
or 
```js
 document.querySelector("#colour").dispatchEvent(new Event('input', { bubbles: true }));
```
