### ISSUE TITLE
Add option to close when I select the color

### ISSUE THREAD

**Issue by enmanuel97** [mdbassit/Coloris#54]
I don't know if there is an option to autoclose the modal when I choose the color, if not I would like(if you want and if you can) the possibility to customize that.

**Comment by mdbassit** [comment]
It is unclear to me when a color is considered selected and the dialog can be closed. Just clicking on the saturation and brightness selector (the gradient) doesn't necessarily mean a color has been selected, as the user might want to tweak the opacity, hue, saturation or brightness. So automatically closing the dialog is not the correct behaviour.

The only case when automatically closing the dialog makes sense, is when the color picker is only showing swatches.
