### ISSUE TITLE
Is there a way to apply different options to different color pickers on the same page?

### ISSUE THREAD

**Issue by angyan** [mdbassit/Coloris#56]

**Comment by melloware** [comment]
You can read how to "sort of" do it here: https://github.com/mdbassit/Coloris/issues/28

**Comment by mdbassit** [comment]
I'm actually working on an implementation of "virtual" instances that should enable color pickers of different styles on the same page. I will code it this Sunday and push it whenever it's ready.
@melloware would you be willing to help me test it?

**Comment by angyan** [comment]
That's a nice solution :)  Thank you @melloware.

**Comment by melloware** [comment]
> I'm actually working on an implementation of "virtual" instances that should enable color pickers of different styles on the same page. I will code it this Sunday and push it whenever it's ready. @melloware would you be willing to help me test it?

Absolutely @mdbassit i will help test it!

**Comment by mdbassit** [comment]
Great, I will push the new code to a separate brunch and let you know.

**Comment by melloware** [comment]
0.15.0 published to NPM
