### ISSUE TITLE
Bug: Color picker sometimes goes off top of screen

### ISSUE THREAD

**Issue by personalizedrefrigerator** [mdbassit/Coloris#57]
# Summary
The color picker goes off the top of the screen when there isn't enough space for it below the input.

For example, with the configuration
```
Coloris({
	el: '.coloris_input',
	format: 'hex',
	selectInput: false,
	focusInput: false,
	themeMode: this.editor.lightMode ? 'light' : 'dark',
	
	swatches: [
		Color4.red.toHexString(),
		Color4.purple.toHexString(),
		Color4.blue.toHexString(),
		Color4.yellow.toHexString(),
		Color4.green.toHexString(),
		Color4.clay.toHexString(),
		Color4.black.toHexString(),
		Color4.white.toHexString(),
	],
});
```
I get,
![Screenshot of the color picker overflowing the top of the screen](https://user-images.githubusercontent.com/46334387/183882130-137a050c-2436-46b1-9b5d-e96b1122b2b5.png)
and
![screenshot of phone in landscape mode, color picker not overflowing](https://user-images.githubusercontent.com/46334387/183882465-a3ddf4d1-f829-4fd4-8389-ba928ade47aa.png)

# Expected Behavior

The color picker should go below the input.

**Comment by mdbassit** [comment]
I'm not sure what you mean by making the color picker scroll.
What I can do now is to position the color picker below the input if there is not enough space above it.

**Comment by personalizedrefrigerator** [comment]
> I'm not sure what you mean by making the color picker scroll. What I can do now is to position the color picker below the input if there is not enough space above it.

Perhaps something like this:
![](https://user-images.githubusercontent.com/46334387/184062813-34ff217e-0fc8-46cd-bec0-f13c0e6cd1b5.png)
(e.g. setting `top` to `max(0px, current-value-of-top)` and `max-width: 100vh`)

**Comment by mdbassit** [comment]
I don't think scrolling is a good idea. It's not a great user experience, but also it's not as easy to implement as it may seem.
I think what you need is a custom theme with the gradient on the left and the other controls on the right. Here is an example of what it might look:

<img width="420" alt="Alternative theme" src="https://user-images.githubusercontent.com/6975607/184092949-c87ea659-72e4-46c2-8641-4dd8952422de.png">

You can then switch between that new theme and default theme whenever the orientation changes.

**Comment by personalizedrefrigerator** [comment]
> I don't think scrolling is a good idea. It's not a great user experience, but also it's not as easy to implement as it may seem. I think what you need is a custom theme with the gradient on the left and the other controls on the right. Here is an example of what it might look:
> 
> <img alt="Alternative theme" width="420" src="https://user-images.githubusercontent.com/6975607/184092949-c87ea659-72e4-46c2-8641-4dd8952422de.png">
> 
> You can then switch between that new theme and default theme whenever the orientation changes.

Good idea!

**Comment by mdbassit** [comment]
I will add that horizontal theme in a little while

**Comment by mdbassit** [comment]
I just pushed a new release with a new theme called "pill" that does what I described above.

**Comment by melloware** [comment]
I just pushed 0.16.0 to NPM with this fix as well. Nice work @mdbassit
