### ISSUE TITLE
Cannot submit form when using coloris 

### ISSUE THREAD

**Issue by natsirasrafi** [mdbassit/Coloris#60]
![Screen Shot 2022-08-20 at 1 54 02 PM](https://user-images.githubusercontent.com/15030656/185733104-39d773d0-9fbe-4a76-8601-f391baf48804.png)

i cannot submit form and get value from input when use coloris

**Comment by mdbassit** [comment]
That is not valid HTML, that's why it doesn't work. Please review the basics of HTML before submitting an issue here.
You need to move `<form action="...` before `<div class="examples">`.
