### ISSUE TITLE
clr-field color does not change when input value change

### ISSUE THREAD

**Issue by balintpipei** [mdbassit/Coloris#61]
Hi, this color widget is awesome, thanks for making it. I used for my project and everything works great except a little details. Maybe I missed something.
When I change the input value the parent element (clr-field) color does not change. 
I tried to replicate it:
https://codepen.io/b-lint-pipei/pen/xxWNmNb

I am sorry if I missed something.
Thanks
Balint

**Comment by mdbassit** [comment]
If you are trying to change the thumbnail color when you programmatically change the value of the input, the documentation describes the way to do it here: https://github.com/mdbassit/Coloris#manually-updating-the-thumbnail

**Comment by balintpipei** [comment]
Thank you.
