### ISSUE TITLE
Inline Mode - Change event not triggering and can't set specified color

### ISSUE THREAD

**Issue by Mukatai** [mdbassit/Coloris#63]
Hello,

Thank you for share your picker.

When i use Coloris in inline mode the input text (#clr-color-value) don't trigger the change event and don't select the color entered. When the picker isn't in inline mode the change event is triggered.

An other problem, always in inline mode, i can't change the select color by code. Can you add a function to update the current color ? Like Coloris.update('#C4C4C4') ou Coloris.set({color:'#C4C4C4'}). I see in source the setColorFromStr() function but it not a public function...

@+

**Comment by mdbassit** [comment]
Thank you for reporting this issue. The first problem is indeed a bug, I will release a fix shortly.

As for the second problem, to change the color programmatically in inline mode, you need to set the value of the input `#clr-color-value`, then trigger a change event on it. Example:
```js
document.querySelector('#clr-color-value').value = 'green';
document.querySelector('#clr-color-value').dispatchEvent(new Event('change', { bubbles: true }));
```
This will work after I release a fix for the first problem.

**Comment by mdbassit** [comment]
The new release fixes this issue

**Comment by Mukatai** [comment]
The new version work perfectly.

Thank you very much for your quick update.
