### ISSUE TITLE
Use of CSS variables `var(--*)` on swatches

### ISSUE THREAD

**Issue by crewstyle** [mdbassit/Coloris#65]
Hi @mdbassit :)

Is there a way to allow us using css `var` function as swatches colors?

I don't use the `input[type="color"]` and I built the swatches through an other way. Here is the result:
```javascript
Coloris({
    // some other options
    swatches: [
        'var(--poseidon-color-1)',
        'var(--poseidon-color-2)',
        'var(--poseidon-color-3)',
        'var(--poseidon-color-4)',
        'var(--poseidon-color-5)',
        'var(--poseidon-color-6)',
        'var(--poseidon-color-7)',
        'var(--poseidon-color-8, "#ffffff")',
    ],
});
```

It's possible to get the var's color simply thanks to: `getComputedStyle(document.documentElement).getPropertyValue('--poseidon-color-1')`

Do you think there is a way to hook the `setColorFromStr` function?

If I select on a swatch instead of picking a color, I need the input to get the variable name (`var(--poseidon-color-1)`) as a result.

Thanks for your feedback.
Achraf

**Comment by mdbassit** [comment]
I don't see a point in doing it that way. But you are welcome to fork the project and customize it as much as you like.
