### ISSUE TITLE
Inline mode with setInstance

### ISSUE THREAD

**Issue by AntonLitvin** [mdbassit/Coloris#67]
Hi!
I tried to set inline mode through setInstance, but it still popup.
maybe i do something wrong?
```
<div class="form-input color-picker color-picker-inline ">
  <label for="cp2">Choose color</label>
  <input id="cp2" type="text" class="instance1" data-coloris>
</div>

Coloris.setInstance('.instance1', {
  parent: '.color-picker-inline',
  theme: 'polaroid',
  inline: true
});
```

**Comment by mdbassit** [comment]
Instances are not supported in inline mode, and similarly, you can not set inline mode using instances. If you need an inline color picker, use the main configuration method.

**Comment by mdbassit** [comment]
There is no way to have multiple inline color pickers.

**Comment by AntonLitvin** [comment]
Thanks, have a good day
