### ISSUE TITLE
Have the color picker without click on an input field

### ISSUE THREAD

**Issue by Merlode11** [mdbassit/Coloris#71]
Hello,

I see your project and it's look really nice for me.

I just wanted to know if I can set that, instead of clicking on a button (the input field) to see the color picker, I can set a defined place for the color picker, to see it all the time on the page.

Thanks for your answer !

**Comment by melloware** [comment]
@Merlode11 you want inline mode: `inline: true`

> // Set to true to use the color picker as an inline widget. In this mode the color picker is
>   // always visible and positioned statically within its container, which is by default the body
>   // of the document. Use the "parent" option to set a custom container.
>   // Note: In this mode, the best way to get the picked color, is listening to the "coloris:pick"
>   // event and reading the value from the event detail (See example in the Events section). The
>   // other way is to read the value of the input field with the id "clr-color-value".
>   inline: false,

**Comment by Merlode11** [comment]
Oh, yes, true thank you very much. I used it in a custom instance, and that was not works well.
I resolved the problem now !
