### ISSUE TITLE
Right To Left Support

### ISSUE THREAD

**Issue by melloware** [mdbassit/Coloris#75]
I think the component should ideally support.

```xml
<input type="text" dir="rtl" data-coloris>
```
 I have it sort of working...

![image](https://user-images.githubusercontent.com/4399574/216770580-5184aeca-9ebc-4e0f-b576-7320c338d6ee.png)

But the HEX code should be on the right but be `#FFFFFFF` not `FFFFFFF#`

Here is some CSS I use by adding `rtl` class to the DIV when the input is detected to be RTL to put the button on the left instead of the right.

```css
body .clr-field  button.rtl {
    right: unset;
}
```

I guess the same goes for RGB and HSL?

**Comment by mdbassit** [comment]
Adding RTL support is a great idea, but I think it should be added as an explicit option.

![](https://user-images.githubusercontent.com/4399574/216770580-5184aeca-9ebc-4e0f-b576-7320c338d6ee.png)

To avoid the issue of the HEX code (and RGB, HSL) being inverted, the input fields themselves should be forced to `ltr` and simply aligned to the right, since the values will always be in a left-to-right language (english).

The rest is easy, I'll just add a right-to-left version to each theme.

**Comment by melloware** [comment]
You are correct. That would be great if there was an explicit rtl=true setting.  Thanks for considering!

**Comment by mdbassit** [comment]
Thank you for suggesting RTL support! I'll implement soon.

**Comment by melloware** [comment]
I am testing this and it seems like its affecting ALL instances not the instance its marked on.

See my recording of the issue:
![rtl](https://user-images.githubusercontent.com/4399574/217017715-f61dfad8-9b31-4237-90cb-7aeb12762366.gif)

**Comment by mdbassit** [comment]
I don't think the `rtl` option should be set per instance, a page is either in right-to-left or it isn't. The only use cases where you want a part of the page only to be right-to-left are demos and snippets. 

In your case, if all you want is one of the color fields to be right-to-left, a better way would be to manually add the `clr-rtl` class to that field, and have the color picker treat it as a right-to-left field, no instance necessary. I will push a commit that implements that and adds the `rtl` option to the unsupported list in instances.

**Comment by melloware** [comment]
This is working great!

**Comment by Binternet** [comment]
my page is `html dir=rtl` which makes the scrollers work in the opposite direction

![CleanShot 2023-02-13 at 14 29 13](https://user-images.githubusercontent.com/438361/218458035-9137efb5-a8f0-45a2-b217-1988067b6316.gif)

**Comment by mdbassit** [comment]
> my page is `html dir=rtl` which makes the scrollers work in the opposite direction
> 

You need to add `rtl: true` to the settings.

**Comment by Binternet** [comment]
@mdbassit i did

**Comment by mdbassit** [comment]
Can you send a link to your page?

**Comment by Binternet** [comment]
its running on localhost, here are the main components.

Like I said - the `html dir=rtl`

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/mdbassit/Coloris@latest/dist/coloris.min.css"/>

                    <div class="row g-3 align-items-center mb-3">
                        <div class="col-auto">
                            <label for="" class="col-form-label">background</label>
                        </div>
                        <div class="col-auto">
                            <input type="text" value="" class="form-control" id="" data-coloris>
                        </div>
                        <div class="col-auto">
                            <span id="" class="form-text"></span>
                        </div>
                    </div>

    <script src="https://cdn.jsdelivr.net/gh/mdbassit/Coloris@latest/dist/coloris.min.js"></script>
    <script>
        $(document).ready(function(e){
            Coloris({
                //themeMode: 'dark',
                rtl: true
            });
        });
    </script>
```

**Comment by mdbassit** [comment]
It looks like jsdelivr hasn't updated the latest version yet. Can you try including the Javascript using this url:

https://cdn.jsdelivr.net/gh/mdbassit/Coloris@v0.18.0/dist/coloris.min.js

**Comment by Binternet** [comment]
Changed, still not working properly.

When I change `html dir=rtl` to `ltr` via console > elements, it works just fine.

**Comment by mdbassit** [comment]
Sorry you need to update the css link as well:

https://cdn.jsdelivr.net/gh/mdbassit/Coloris@v0.18.0/dist/coloris.min.css

**Comment by Binternet** [comment]
Works! thank you very much!
