### ISSUE TITLE
Add `name` to input fields

### ISSUE THREAD

**Issue by melloware** [mdbassit/Coloris#76]
I have been doing some testing this week with my and form input.  For `inline` input when I submit a form only 1 of the input values is being sent in the form submit.

Just this value is being sent.
![image](https://user-images.githubusercontent.com/4399574/216848272-48275309-acb3-40e4-b069-a6723fc06d45.png)

IF I add `name` props to the rest of the input fields then I can see the rest of the values in Form Submit.

![image](https://user-images.githubusercontent.com/4399574/216848315-13151879-fea4-4357-8b03-0979786f13e6.png)

This would be preferable so in `inline` mode I can just get the selected color.

**Comment by mdbassit** [comment]
I admit that I don't usually use (and therefore prioritize) `inline` mode, so I haven't tested it extensively. I didn't think of rendering the color picker inside a form all.
