### ISSUE TITLE
Custom function

### ISSUE THREAD

**Issue by ReqwareInc** [mdbassit/Coloris#83]
Can I make a custom function work when I select a color for each color picker instance?

**Comment by melloware** [comment]
Yes you can.  I am doing that. Just subscribe to "color.pick" event on your input instead of on "document" and you can get only when the color is picked on that instance.

**Comment by mdbassit** [comment]
> Yes you can. I am doing that. Just subscribe to "color.pick" event on your input instead of on "document" and you can get only when the color is picked on that instance.

I'm not sure that works. If you mean the `coloris:pick` event, that one is triggered on the document itself and will not be captured on the individual input fields of an instance.

To answer @ReqwareInc's question, you can simply listen to an `input` event on the fields of your instance like this:

```js
document.querySelectorAll('.myInstance').forEach(field => {
  field.addEventListener('input', myCustomFunction);
});
```

**Comment by melloware** [comment]
Are you sure it doesn't work?  I have 5 color pickers on my page and I do this

```JS

$this.input.on('coloris:pick', function(e) {
                $this.callBehavior('change');
            });
```

And I only get notified 1 time not five times when a color is picked?

**Comment by mdbassit** [comment]
That can be a perk of whatever library/framework your are using to add event listeners. I'm fairly certain it won't work with vanilla Javascript. Try it with addEventListener.

**Comment by mdbassit** [comment]
Since this kind of custom action when a color is picked can be quite useful, I decided to implement a new `onChange` callback that can be set to a custom function for each instance. I will push the code soon.

**Comment by ReqwareInc** [comment]
This is what I was hoping for!
It is very easy to extend.
I have confirmed that it works just fine.
