### ISSUE TITLE
Rails 7 with Turbo: Coloris doesn't initialize correctly

### ISSUE THREAD

**Issue by mhuegel** [mdbassit/Coloris#84]
I use Coloris in a small Rails 7 app with Turbo enabled.
On the first page load / page refresh everything is working fine. But after navigation to another page, Coloris doesn't bind to the input fields and after focusing the input the following error appears:

`Uncaught TypeError: Cannot set properties of null (setting 'checked')`

I tried to re-initialize Coloris by calling

```
$(document).on('turbo:load', function () {
	Coloris({
		alpha: false,
		swatches: ['#264653', '#2a9d8f', '#e9c46a']
	});
});
```

But that doesn't work either. Do you have any suggestions or workarounds?

**Comment by mdbassit** [comment]
Please link to a page where I can reproduce the issue.

**Comment by elalemanyo** [comment]
@mhuegel I am using Coloris in a Rails 7 app with Turbo and it works perfectly.
This is how I am doing it, maybe helps you:
```js
import Coloris from '@melloware/coloris'

document.addEventListener('turbo:load', function () {
  const colorisElements = document.querySelectorAll('[data-coloris]')
  if (colorisElements) {
    Coloris.init()
    Coloris({
      theme: 'polaroid',
      themeMode: 'light',
      alpha: false,
      wrap: false,
      clearButton: false
    })
  }
})
```

BTW: I am working on a stimulus wrapper 🙂

**Comment by mhuegel** [comment]
@mdbassit That's not possible at the moment, because it's all tied to Shopify Login Credentials but i recorded a short video that shows the behaviour: https://www.loom.com/share/9205902f5f524a73b23c3b36a2fee78e

My observation so far: turbo replaces the whole body-element while switching pages, so the #clr-picker div gets lost in the process.
