### ISSUE TITLE
Feature Request: Constrain Focus on Color Picker Dialog

### ISSUE THREAD

**Issue by gautamo** [mdbassit/Coloris#87]
Hi, would it be possible to constrain the focus on the color picker dialog when it is opened. This way, using the tab key will continue to cycle through the color picker dialog options until either the escape key is clicked or close button is selected using the keyboard.

**Comment by melloware** [comment]
Not a bad idea.  It's usually referred to as a "focus trap" when you want to keep the focus inside the popup while it's open.

**Comment by mdbassit** [comment]
That's actually a bad idea for accessibility. The color picker dialog is not a modal, you can still interact with the rest of the page while it's open. Using a focus trap means users using keyboard only navigation will have less access to the page and the browser controls than users using a mouse/touchpad.

**Comment by Ani-Soft** [comment]
Hi, Is there anyway to set color on already initiated colorpicker instance ?
Something like setColor() or updateColor() etc.

**Comment by melloware** [comment]
@Ani-Soft i don't know if there is a better way but I wrote my own custom method to do it.

```js
  /**
   * Copy the active color to the linked input field and set the color.
   * @param {string} [color] Color value to override the active color.
   * @param {HTMLelement} [target] the element setting the color on
   */
  function setColor(color, target) {
    currentEl = target;
    oldColor = currentEl.value;
    attachVirtualInstance(target);
    currentFormat = getColorFormatFromStr(color);
    updatePickerPosition();
    setColorFromStr(color);
    pickColor();
    if (oldColor !== color) {
       currentEl.dispatchEvent(new Event('change', { bubbles: true }));
    }
  }
```

**Comment by mdbassit** [comment]
> Hi, Is there anyway to set color on already initiated colorpicker instance ? Something like setColor() or updateColor() etc.

Could you please create a separate issue please? Your question is unrelated to this one!
Are you using the color picker in normal or inline mode?

**Comment by melloware** [comment]
Done: https://github.com/mdbassit/Coloris/issues/91

This ticket can be closed.
