### ISSUE TITLE
bug when using selectInput: true

### ISSUE THREAD

**Issue by jordanharding** [mdbassit/Coloris#88]
Really nice work!

Found a small bug. When selectInput: true is enabled, typing any color will always translate to black on input. But then works fine after the first hit. 

Would also be nice if there was a way to define whether or not the selection should include the # when using hex.

**Comment by mdbassit** [comment]
> Really nice work!

Thank you!

> Found a small bug. When selectInput: true is enabled, typing any color will always translate to black on input. But then works fine after the first hit.

I'm not sure I understand! Typing a color's name or code works well for me. Could you please explain how to reproduce the issue?

> Would also be nice if there was a way to define whether or not the selection should include the # when using hex.

I will see what I can do.

**Comment by jordanharding** [comment]
Looks like the issue might have been on my end as I can no longer reproduce the issue. Thanks for the quick response!
