### ISSUE TITLE
Feature request: Add a way to update color on hex color change

### ISSUE THREAD

**Issue by adamscott** [mdbassit/Coloris#90]
It would be nice if there was a way to update the color on hex color change.

Currently, as shown in the image below, the color will only update on "Enter" or if the widget loses the focus.

![image](https://user-images.githubusercontent.com/270928/223523397-7e2607d1-ab7e-4046-9fd2-490ab6665e98.png)

**Comment by mdbassit** [comment]
The way this color picker is implemented will make that hard to do in an efficient way. Sorry!
