### ISSUE TITLE
Feature Request: Pipette / Eye Dropper

### ISSUE THREAD

**Issue by anthony0030** [mdbassit/Coloris#95]
It would be great to have an eye dropper in the color picker

**Comment by mdbassit** [comment]
Unfortunately the EyeDropper API is still experimental and is only supported on some chromium based browsers. I will revisit again when it becomes a standard or at least supported by all modern browsers.

**Comment by anthony0030** [comment]
Hi @mdbassit, That sounds fair :)
Thanks for the great tool!
