### ISSUE TITLE
Display Value color after refresh page

### ISSUE THREAD

**Issue by amonam** [mdbassit/Coloris#97]
I have a default color value of "#202124" and I use JavaScript to programmatically change it to "#ff0000" when the page refreshes. However, when I check the HTML in the console, it shows that the selected color has been changed, but it does not reflect on the screen.

![darkmode](https://user-images.githubusercontent.com/19654690/235210274-5b26faad-006b-4cb3-8957-02363700a8ba.png)

Here are the code snippets:
The input element has a class "bg_color_input_Class" and a default value of "#202124".

I use the JavaScript code below to change the value to "#ff0000":
var inputElementBgColorDark = document.getElementById("background_color_dark");
inputElementBgColorDark.setAttribute("value", "#ff0000");

Could you give me a little clue on how to fix it?

**Comment by mdbassit** [comment]
The solution is in the "Manually updating the thumbnail" section of the README.
https://github.com/mdbassit/Coloris#manually-updating-the-thumbnail
